In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
first_array=np.array([[1,2,3],[4,5,6]])
second_array=np.array([[10,11,12],[13,14,15]])
print(np.add(first_array,second_array))

[[11 13 15]
 [17 19 21]]


In [4]:
array=np.array([[1,2,3],[4,5,6]])
print(np.multiply(array,2))

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
array1D = np.array([
    0, 1, 2,
    3, 4, 5,
    6, 7, 8,
    9, 10, 11,
    12, 13, 14,
    15, 16, 17,
    18, 19, 20,
    21, 22, 23,
    24, 25, 25
])

array3D = array1D.reshape(3, 3, 3)
print(array3D)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 25]]]


In [7]:
original_array = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])
print('original array:', original_array)

integer_datatype_array = original_array.astype(int)
print('Integer datatype array:', integer_datatype_array)

original array: [[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]
Integer datatype array: [[2 3 1]
 [4 2 1]]


In [8]:
original_array = np.array([[1, 1, 0], [0, 1, 0], [0, 1, 0]])
print('Original array:')
print(original_array)

boolean_array = original_array.astype(bool)
print('Boolean array:')
print(boolean_array)


Original array:
[[1 1 0]
 [0 1 0]
 [0 1 0]]
Boolean array:
[[ True  True False]
 [False  True False]
 [False  True False]]


In [9]:
arr1 = np.array(
  [[1, 4],
   [2, 5],
   [3, 6]])

arr2 = np.array(
  [[7, 10],
   [8, 11],
   [9, 12]])

print(np.hstack((arr1, arr2)))


[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [10]:
array = np.arange(0, 102, 2)  
print(array)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [11]:
rand_array = np.random.rand(1000000)

sum_loop = 0
for i in rand_array:
    sum_loop += i

print("Sum using loop:", sum_loop)

sum_numpy = np.sum(rand_array)
print("Sum using NumPy sum:", sum_numpy)

Sum using loop: 499916.0418353771
Sum using NumPy sum: 499916.04183541


In [13]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([1, 3, 2, 4, 5])

result = np.where(array_1 == array_2)
print(result)

(array([0, 3, 4]),)


In [14]:
array = np.linspace(0, 100, 5)
print(array)

[  0.  25.  50.  75. 100.]


In [15]:
print(np.full((2, 3), 5))

[[5 5 5]
 [5 5 5]]


In [16]:
array = np.random.randint(0, 11, size=(5, 5))
print(array)

[[ 6  2  7  1  0]
 [ 0 10  7  5  0]
 [ 2  6  4  8  4]
 [ 8  9  2  3  0]
 [ 6  5  7  1  1]]


In [17]:
array_1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

array_2 = np.array([[2, 3, 4],
                 [5, 6, 7],
                 [8, 9, 10]])

print(np.dot(array_1, array_2))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [18]:
matrix = np.random.rand(2, 3)
print("Original 2x3 matrix:")
print(matrix)

transpose_matrix = matrix.T
print("\nTransposed matrix (3x2):")
print(transpose_matrix)

Original 2x3 matrix:
[[0.84998647 0.8523208  0.7151393 ]
 [0.16842185 0.7884519  0.88695103]]

Transposed matrix (3x2):
[[0.84998647 0.16842185]
 [0.8523208  0.7884519 ]
 [0.7151393  0.88695103]]


In [19]:
arr = np.array([
    [2, 2, 2, 2, 2],
    [15, 6, 27, 8, 2],
    [23, 2, 54, 1, 2],
    [11, 44, 34, 7, 2]
])

print('flatten:', np.std(arr))
print('axis 0:', np.std(arr, axis=0))
print('axis 1:', np.std(arr, axis=1))


flatten: 15.3668474320532
axis 0: [ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]
axis 1: [ 0.          8.7772433  20.53874388 16.40243884]


In [20]:
arr = np.array([[6, 1, 1],
                [4, -2, 5],
                [2, 8, 7]])

print(np.linalg.inv(arr))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [21]:
!pip install pillow

In [23]:
from PIL import Image
import numpy as np

image = Image.open('Nature.jpeg')
image_array = np.array(image)

print(image_array)
print("Shape:", image_array.shape)


[[[ 75  13  16]
  [ 80   2  15]
  [ 96   3  24]
  ...
  [103  43  43]
  [ 83  24  18]
  [ 84  39  36]]

 [[ 65   0   0]
  [ 79   1  15]
  [ 75   3  17]
  ...
  [ 89  49  60]
  [ 97  56  64]
  [ 73  40  47]]

 [[ 51   4  12]
  [ 57   7  16]
  [ 52   5  11]
  ...
  [103  84 103]
  [ 62  38  54]
  [ 52  26  39]]

 ...

 [[127 126 144]
  [127 126 144]
  [128 127 145]
  ...
  [ 81  94 126]
  [ 81  94 126]
  [ 81  94 126]]

 [[110 115 135]
  [111 116 136]
  [111 116 136]
  ...
  [ 79  92 126]
  [ 79  92 126]
  [ 79  92 126]]

 [[102 108 132]
  [102 108 132]
  [102 108 132]
  ...
  [ 79  92 126]
  [ 79  92 126]
  [ 79  92 126]]]
Shape: (144, 349, 3)


In [24]:
data = {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216}
arr = np.array(list(data.values()))
print(arr)

[  0   1   8  27  64 125 216]


In [25]:
a=np.array([[3,1,-2],[2,-1,1],[1,2,3]])
b=np.array([9,3,12])
solutions=np.linalg.solve(a,b)
print("Solution:",solutions)

Solution: [2.6 3.2 1. ]


In [26]:
array = np.random.rand(3, 3, 3)
print("Original 3x3x3 array:\n", array)

flattened = array.flatten()
print("\nFlattened 1D array:\n", flattened)

Original 3x3x3 array:
 [[[0.30028218 0.16807508 0.82294058]
  [0.6921286  0.99143298 0.60693198]
  [0.06150559 0.78961715 0.84591723]]

 [[0.85063005 0.65802659 0.15898614]
  [0.25076472 0.0913909  0.5955827 ]
  [0.89883721 0.63085386 0.36054313]]

 [[0.92257448 0.99912789 0.22430309]
  [0.92749602 0.9089736  0.14328293]
  [0.92739043 0.83573995 0.737144  ]]]

Flattened 1D array:
 [0.30028218 0.16807508 0.82294058 0.6921286  0.99143298 0.60693198
 0.06150559 0.78961715 0.84591723 0.85063005 0.65802659 0.15898614
 0.25076472 0.0913909  0.5955827  0.89883721 0.63085386 0.36054313
 0.92257448 0.99912789 0.22430309 0.92749602 0.9089736  0.14328293
 0.92739043 0.83573995 0.737144  ]


In [30]:
array = np.random.rand(3, 3)
print("Original 3x3 array:\n", array)

distances = np.linalg.norm(array[:, np.newaxis] - array, axis=2)
print("\nPairwise Euclidean distance between rows:\n", distances)


Original 3x3 array:
 [[0.63116243 0.48581505 0.79922157]
 [0.34197691 0.62158558 0.07665447]
 [0.40049685 0.50573015 0.53193988]]

Pairwise Euclidean distance between rows:
 [[0.         0.79004122 0.35361381]
 [0.79004122 0.         0.47342568]
 [0.35361381 0.47342568 0.        ]]
